// Code generated by protoc-gen-go.
// source: inventory.proto
// DO NOT EDIT!

package pogo_protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Ignoring public import of ItemData from inventory_item.proto

// Ignoring public import of ItemAward from inventory_item.proto

// Ignoring public import of ItemId from inventory_item.proto

// Ignoring public import of ItemType from inventory_item.proto

// Ignoring public import of AssetDigestEntry from data.proto

// Ignoring public import of PokemonData from data.proto

// Ignoring public import of PokedexEntry from data.proto

// Ignoring public import of DownloadUrlEntry from data.proto

// Ignoring public import of PlayerBadge from data.proto

// Ignoring public import of PlayerData from data.proto

// Ignoring public import of DailyBonus from data_player.proto

// Ignoring public import of ContactSettings from data_player.proto

// Ignoring public import of EquippedBadge from data_player.proto

// Ignoring public import of Currency from data_player.proto

// Ignoring public import of PlayerPublicProfile from data_player.proto

// Ignoring public import of PlayerStats from data_player.proto

// Ignoring public import of PlayerCamera from data_player.proto

// Ignoring public import of PlayerAvatar from data_player.proto

// Ignoring public import of PlayerCurrency from data_player.proto

// Ignoring public import of PokemonMovementType from enums.proto

// Ignoring public import of HoloIapItemCategory from enums.proto

// Ignoring public import of PokemonMove from enums.proto

// Ignoring public import of ItemCategory from enums.proto

// Ignoring public import of CameraInterpolation from enums.proto

// Ignoring public import of TutorialState from enums.proto

// Ignoring public import of ItemEffect from enums.proto

// Ignoring public import of Platform from enums.proto

// Ignoring public import of BadgeType from enums.proto

// Ignoring public import of PokemonRarity from enums.proto

// Ignoring public import of PokemonFamilyId from enums.proto

// Ignoring public import of PokemonType from enums.proto

// Ignoring public import of TeamColor from enums.proto

// Ignoring public import of ActivityType from enums.proto

// Ignoring public import of CameraTarget from enums.proto

// Ignoring public import of Gender from enums.proto

// Ignoring public import of PokemonId from enums.proto

type InventoryUpgradeType int32

const (
	InventoryUpgradeType_UPGRADE_UNSET            InventoryUpgradeType = 0
	InventoryUpgradeType_INCREASE_ITEM_STORAGE    InventoryUpgradeType = 1
	InventoryUpgradeType_INCREASE_POKEMON_STORAGE InventoryUpgradeType = 2
)

var InventoryUpgradeType_name = map[int32]string{
	0: "UPGRADE_UNSET",
	1: "INCREASE_ITEM_STORAGE",
	2: "INCREASE_POKEMON_STORAGE",
}
var InventoryUpgradeType_value = map[string]int32{
	"UPGRADE_UNSET":            0,
	"INCREASE_ITEM_STORAGE":    1,
	"INCREASE_POKEMON_STORAGE": 2,
}

func (x InventoryUpgradeType) String() string {
	return proto.EnumName(InventoryUpgradeType_name, int32(x))
}
func (InventoryUpgradeType) EnumDescriptor() ([]byte, []int) { return fileDescriptor9, []int{0} }

type EggIncubatorType int32

const (
	EggIncubatorType_INCUBATOR_UNSET    EggIncubatorType = 0
	EggIncubatorType_INCUBATOR_DISTANCE EggIncubatorType = 1
)

var EggIncubatorType_name = map[int32]string{
	0: "INCUBATOR_UNSET",
	1: "INCUBATOR_DISTANCE",
}
var EggIncubatorType_value = map[string]int32{
	"INCUBATOR_UNSET":    0,
	"INCUBATOR_DISTANCE": 1,
}

func (x EggIncubatorType) String() string {
	return proto.EnumName(EggIncubatorType_name, int32(x))
}
func (EggIncubatorType) EnumDescriptor() ([]byte, []int) { return fileDescriptor9, []int{1} }

type InventoryDelta struct {
	OriginalTimestampMs int64            `protobuf:"varint,1,opt,name=original_timestamp_ms,json=originalTimestampMs" json:"original_timestamp_ms,omitempty"`
	NewTimestampMs      int64            `protobuf:"varint,2,opt,name=new_timestamp_ms,json=newTimestampMs" json:"new_timestamp_ms,omitempty"`
	InventoryItems      []*InventoryItem `protobuf:"bytes,3,rep,name=inventory_items,json=inventoryItems" json:"inventory_items,omitempty"`
}

func (m *InventoryDelta) Reset()                    { *m = InventoryDelta{} }
func (m *InventoryDelta) String() string            { return proto.CompactTextString(m) }
func (*InventoryDelta) ProtoMessage()               {}
func (*InventoryDelta) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{0} }

func (m *InventoryDelta) GetInventoryItems() []*InventoryItem {
	if m != nil {
		return m.InventoryItems
	}
	return nil
}

type InventoryItemData struct {
	PokemonData       *PokemonData       `protobuf:"bytes,1,opt,name=pokemon_data,json=pokemonData" json:"pokemon_data,omitempty"`
	Item              *ItemData          `protobuf:"bytes,2,opt,name=item" json:"item,omitempty"`
	PokedexEntry      *PokedexEntry      `protobuf:"bytes,3,opt,name=pokedex_entry,json=pokedexEntry" json:"pokedex_entry,omitempty"`
	PlayerStats       *PlayerStats       `protobuf:"bytes,4,opt,name=player_stats,json=playerStats" json:"player_stats,omitempty"`
	PlayerCurrency    *PlayerCurrency    `protobuf:"bytes,5,opt,name=player_currency,json=playerCurrency" json:"player_currency,omitempty"`
	PlayerCamera      *PlayerCamera      `protobuf:"bytes,6,opt,name=player_camera,json=playerCamera" json:"player_camera,omitempty"`
	InventoryUpgrades *InventoryUpgrades `protobuf:"bytes,7,opt,name=inventory_upgrades,json=inventoryUpgrades" json:"inventory_upgrades,omitempty"`
	AppliedItems      *AppliedItems      `protobuf:"bytes,8,opt,name=applied_items,json=appliedItems" json:"applied_items,omitempty"`
	EggIncubators     *EggIncubators     `protobuf:"bytes,9,opt,name=egg_incubators,json=eggIncubators" json:"egg_incubators,omitempty"`
	Candy             *Candy             `protobuf:"bytes,10,opt,name=candy" json:"candy,omitempty"`
}

func (m *InventoryItemData) Reset()                    { *m = InventoryItemData{} }
func (m *InventoryItemData) String() string            { return proto.CompactTextString(m) }
func (*InventoryItemData) ProtoMessage()               {}
func (*InventoryItemData) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{1} }

func (m *InventoryItemData) GetPokemonData() *PokemonData {
	if m != nil {
		return m.PokemonData
	}
	return nil
}

func (m *InventoryItemData) GetItem() *ItemData {
	if m != nil {
		return m.Item
	}
	return nil
}

func (m *InventoryItemData) GetPokedexEntry() *PokedexEntry {
	if m != nil {
		return m.PokedexEntry
	}
	return nil
}

func (m *InventoryItemData) GetPlayerStats() *PlayerStats {
	if m != nil {
		return m.PlayerStats
	}
	return nil
}

func (m *InventoryItemData) GetPlayerCurrency() *PlayerCurrency {
	if m != nil {
		return m.PlayerCurrency
	}
	return nil
}

func (m *InventoryItemData) GetPlayerCamera() *PlayerCamera {
	if m != nil {
		return m.PlayerCamera
	}
	return nil
}

func (m *InventoryItemData) GetInventoryUpgrades() *InventoryUpgrades {
	if m != nil {
		return m.InventoryUpgrades
	}
	return nil
}

func (m *InventoryItemData) GetAppliedItems() *AppliedItems {
	if m != nil {
		return m.AppliedItems
	}
	return nil
}

func (m *InventoryItemData) GetEggIncubators() *EggIncubators {
	if m != nil {
		return m.EggIncubators
	}
	return nil
}

func (m *InventoryItemData) GetCandy() *Candy {
	if m != nil {
		return m.Candy
	}
	return nil
}

type EggIncubator struct {
	Id             string           `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	ItemId         ItemId           `protobuf:"varint,2,opt,name=item_id,json=itemId,enum=POGOProtos.Inventory.Item.ItemId" json:"item_id,omitempty"`
	IncubatorType  EggIncubatorType `protobuf:"varint,3,opt,name=incubator_type,json=incubatorType,enum=POGOProtos.Inventory.EggIncubatorType" json:"incubator_type,omitempty"`
	UsesRemaining  int32            `protobuf:"varint,4,opt,name=uses_remaining,json=usesRemaining" json:"uses_remaining,omitempty"`
	PokemonId      uint64           `protobuf:"varint,5,opt,name=pokemon_id,json=pokemonId" json:"pokemon_id,omitempty"`
	StartKmWalked  float64          `protobuf:"fixed64,6,opt,name=start_km_walked,json=startKmWalked" json:"start_km_walked,omitempty"`
	TargetKmWalked float64          `protobuf:"fixed64,7,opt,name=target_km_walked,json=targetKmWalked" json:"target_km_walked,omitempty"`
}

func (m *EggIncubator) Reset()                    { *m = EggIncubator{} }
func (m *EggIncubator) String() string            { return proto.CompactTextString(m) }
func (*EggIncubator) ProtoMessage()               {}
func (*EggIncubator) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{2} }

type AppliedItem struct {
	ItemId    ItemId   `protobuf:"varint,1,opt,name=item_id,json=itemId,enum=POGOProtos.Inventory.Item.ItemId" json:"item_id,omitempty"`
	ItemType  ItemType `protobuf:"varint,2,opt,name=item_type,json=itemType,enum=POGOProtos.Inventory.Item.ItemType" json:"item_type,omitempty"`
	ExpireMs  int64    `protobuf:"varint,3,opt,name=expire_ms,json=expireMs" json:"expire_ms,omitempty"`
	AppliedMs int64    `protobuf:"varint,4,opt,name=applied_ms,json=appliedMs" json:"applied_ms,omitempty"`
}

func (m *AppliedItem) Reset()                    { *m = AppliedItem{} }
func (m *AppliedItem) String() string            { return proto.CompactTextString(m) }
func (*AppliedItem) ProtoMessage()               {}
func (*AppliedItem) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{3} }

type EggIncubators struct {
	EggIncubator []*EggIncubator `protobuf:"bytes,1,rep,name=egg_incubator,json=eggIncubator" json:"egg_incubator,omitempty"`
}

func (m *EggIncubators) Reset()                    { *m = EggIncubators{} }
func (m *EggIncubators) String() string            { return proto.CompactTextString(m) }
func (*EggIncubators) ProtoMessage()               {}
func (*EggIncubators) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{4} }

func (m *EggIncubators) GetEggIncubator() []*EggIncubator {
	if m != nil {
		return m.EggIncubator
	}
	return nil
}

type AppliedItems struct {
	Item []*AppliedItem `protobuf:"bytes,4,rep,name=item" json:"item,omitempty"`
}

func (m *AppliedItems) Reset()                    { *m = AppliedItems{} }
func (m *AppliedItems) String() string            { return proto.CompactTextString(m) }
func (*AppliedItems) ProtoMessage()               {}
func (*AppliedItems) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{5} }

func (m *AppliedItems) GetItem() []*AppliedItem {
	if m != nil {
		return m.Item
	}
	return nil
}

type InventoryUpgrade struct {
	ItemId            ItemId               `protobuf:"varint,1,opt,name=item_id,json=itemId,enum=POGOProtos.Inventory.Item.ItemId" json:"item_id,omitempty"`
	UpgradeType       InventoryUpgradeType `protobuf:"varint,2,opt,name=upgrade_type,json=upgradeType,enum=POGOProtos.Inventory.InventoryUpgradeType" json:"upgrade_type,omitempty"`
	AdditionalStorage int32                `protobuf:"varint,3,opt,name=additional_storage,json=additionalStorage" json:"additional_storage,omitempty"`
}

func (m *InventoryUpgrade) Reset()                    { *m = InventoryUpgrade{} }
func (m *InventoryUpgrade) String() string            { return proto.CompactTextString(m) }
func (*InventoryUpgrade) ProtoMessage()               {}
func (*InventoryUpgrade) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{6} }

type InventoryItem struct {
	ModifiedTimestampMs int64              `protobuf:"varint,1,opt,name=modified_timestamp_ms,json=modifiedTimestampMs" json:"modified_timestamp_ms,omitempty"`
	DeletedItemKey      int64              `protobuf:"varint,2,opt,name=deleted_item_key,json=deletedItemKey" json:"deleted_item_key,omitempty"`
	InventoryItemData   *InventoryItemData `protobuf:"bytes,3,opt,name=inventory_item_data,json=inventoryItemData" json:"inventory_item_data,omitempty"`
}

func (m *InventoryItem) Reset()                    { *m = InventoryItem{} }
func (m *InventoryItem) String() string            { return proto.CompactTextString(m) }
func (*InventoryItem) ProtoMessage()               {}
func (*InventoryItem) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{7} }

func (m *InventoryItem) GetInventoryItemData() *InventoryItemData {
	if m != nil {
		return m.InventoryItemData
	}
	return nil
}

type InventoryUpgrades struct {
	InventoryUpgrades []*InventoryUpgrade `protobuf:"bytes,1,rep,name=inventory_upgrades,json=inventoryUpgrades" json:"inventory_upgrades,omitempty"`
}

func (m *InventoryUpgrades) Reset()                    { *m = InventoryUpgrades{} }
func (m *InventoryUpgrades) String() string            { return proto.CompactTextString(m) }
func (*InventoryUpgrades) ProtoMessage()               {}
func (*InventoryUpgrades) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{8} }

func (m *InventoryUpgrades) GetInventoryUpgrades() []*InventoryUpgrade {
	if m != nil {
		return m.InventoryUpgrades
	}
	return nil
}

type Candy struct {
	FamilyId PokemonFamilyId `protobuf:"varint,1,opt,name=family_id,json=familyId,enum=POGOProtos.Enums.PokemonFamilyId" json:"family_id,omitempty"`
	Candy    int32           `protobuf:"varint,2,opt,name=candy" json:"candy,omitempty"`
}

func (m *Candy) Reset()                    { *m = Candy{} }
func (m *Candy) String() string            { return proto.CompactTextString(m) }
func (*Candy) ProtoMessage()               {}
func (*Candy) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{9} }

func init() {
	proto.RegisterType((*InventoryDelta)(nil), "POGOProtos.Inventory.InventoryDelta")
	proto.RegisterType((*InventoryItemData)(nil), "POGOProtos.Inventory.InventoryItemData")
	proto.RegisterType((*EggIncubator)(nil), "POGOProtos.Inventory.EggIncubator")
	proto.RegisterType((*AppliedItem)(nil), "POGOProtos.Inventory.AppliedItem")
	proto.RegisterType((*EggIncubators)(nil), "POGOProtos.Inventory.EggIncubators")
	proto.RegisterType((*AppliedItems)(nil), "POGOProtos.Inventory.AppliedItems")
	proto.RegisterType((*InventoryUpgrade)(nil), "POGOProtos.Inventory.InventoryUpgrade")
	proto.RegisterType((*InventoryItem)(nil), "POGOProtos.Inventory.InventoryItem")
	proto.RegisterType((*InventoryUpgrades)(nil), "POGOProtos.Inventory.InventoryUpgrades")
	proto.RegisterType((*Candy)(nil), "POGOProtos.Inventory.Candy")
	proto.RegisterEnum("POGOProtos.Inventory.InventoryUpgradeType", InventoryUpgradeType_name, InventoryUpgradeType_value)
	proto.RegisterEnum("POGOProtos.Inventory.EggIncubatorType", EggIncubatorType_name, EggIncubatorType_value)
}

func init() { proto.RegisterFile("inventory.proto", fileDescriptor9) }

var fileDescriptor9 = []byte{
	// 1005 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xa4, 0x56, 0xdd, 0x6f, 0x1b, 0x45,
	0x10, 0xef, 0xd9, 0x71, 0x12, 0x8f, 0xed, 0x4b, 0xbc, 0x49, 0x91, 0xe9, 0x87, 0xd4, 0x5c, 0x21,
	0x44, 0x91, 0xea, 0x8a, 0x20, 0x84, 0xc4, 0x03, 0xc5, 0x49, 0xae, 0x91, 0x09, 0x8e, 0xad, 0xb5,
	0x4d, 0x11, 0x12, 0x5a, 0x6d, 0x7c, 0x9b, 0x63, 0x89, 0xef, 0x43, 0x77, 0x67, 0x5a, 0xff, 0x6f,
	0xbc, 0xf0, 0x02, 0x2f, 0xbc, 0xf2, 0xff, 0xb0, 0x1f, 0x77, 0xf6, 0xd9, 0x38, 0x75, 0x50, 0x9f,
	0x3c, 0x33, 0xfb, 0xbb, 0xdf, 0xee, 0xcc, 0xfe, 0x76, 0xc6, 0xb0, 0xc3, 0xfd, 0xdf, 0x98, 0x9f,
	0x04, 0xd1, 0xb4, 0x19, 0x46, 0x41, 0x12, 0xa0, 0xfd, 0x5e, 0xf7, 0xa2, 0xdb, 0x93, 0x66, 0xdc,
	0x6c, 0x67, 0x6b, 0x8f, 0xf6, 0x67, 0x30, 0xc2, 0x13, 0xe6, 0x69, 0xec, 0x23, 0x70, 0x68, 0x42,
	0x53, 0xbb, 0x2e, 0x6d, 0x12, 0x8e, 0xe9, 0x94, 0x45, 0x69, 0xa8, 0xc2, 0xfc, 0x89, 0x17, 0x6b,
	0xc7, 0xfa, 0xdd, 0x00, 0x73, 0xc6, 0x77, 0xce, 0xc6, 0x09, 0x45, 0x27, 0xf0, 0x30, 0x88, 0xb8,
	0xcb, 0x7d, 0x3a, 0x26, 0x09, 0xf7, 0x58, 0x9c, 0x50, 0x2f, 0x24, 0x5e, 0xdc, 0x30, 0x9e, 0x19,
	0x47, 0x45, 0xbc, 0x97, 0x2d, 0x0e, 0xb2, 0xb5, 0x4e, 0x8c, 0x8e, 0x60, 0xd7, 0x67, 0x6f, 0x17,
	0xe1, 0x05, 0x05, 0x37, 0x45, 0x3c, 0x8f, 0xfc, 0x3e, 0x97, 0x9b, 0x3a, 0x74, 0xdc, 0x28, 0x3e,
	0x2b, 0x1e, 0x55, 0x4e, 0x9e, 0x37, 0x57, 0xa5, 0x38, 0xb7, 0xda, 0x02, 0x8b, 0x4d, 0x9e, 0x77,
	0x63, 0xeb, 0x9f, 0x12, 0xd4, 0x17, 0x10, 0xe7, 0x22, 0x5d, 0xf4, 0x0a, 0xaa, 0x61, 0x70, 0xcb,
	0xbc, 0xc0, 0x27, 0x32, 0x7d, 0x75, 0xf0, 0xca, 0xc9, 0x93, 0xfc, 0x06, 0x12, 0xd7, 0xec, 0x69,
	0x90, 0xb4, 0x71, 0x25, 0x9c, 0x3b, 0xe8, 0x2b, 0xd8, 0x90, 0x47, 0x53, 0x29, 0xdc, 0x7d, 0x32,
	0x59, 0xf1, 0x6c, 0x4f, 0xac, 0x3e, 0x40, 0xa7, 0x50, 0x93, 0x3c, 0x0e, 0x7b, 0x47, 0x04, 0x2a,
	0x9a, 0x8a, 0xdc, 0x24, 0xc3, 0xd3, 0x95, 0x5b, 0x0b, 0x94, 0x2d, 0x41, 0xb8, 0x1a, 0xe6, 0x3c,
	0xf4, 0x5a, 0x9c, 0x5e, 0xdd, 0x17, 0x11, 0x35, 0x4b, 0xe2, 0xc6, 0xc6, 0x7f, 0x0f, 0xa1, 0x29,
	0xf4, 0xa5, 0xea, 0x9f, 0xbe, 0x84, 0x8a, 0x24, 0xe6, 0x0e, 0xea, 0xc2, 0x4e, 0xca, 0x33, 0x9a,
	0x44, 0x11, 0xf3, 0x47, 0xd3, 0x46, 0x49, 0x51, 0x1d, 0xbe, 0x9f, 0xea, 0x2c, 0x45, 0x63, 0x33,
	0x5c, 0xf0, 0x51, 0x5b, 0x24, 0x97, 0x12, 0x52, 0x8f, 0x45, 0xb4, 0xb1, 0xa9, 0xe8, 0x3e, 0x59,
	0x43, 0xa7, 0xb0, 0x38, 0xcd, 0x49, 0x7b, 0xe8, 0x07, 0x40, 0x73, 0x15, 0x4c, 0x42, 0x37, 0xa2,
	0x0e, 0x8b, 0x1b, 0x5b, 0x8a, 0xef, 0xb3, 0x35, 0x42, 0x18, 0xa6, 0x70, 0x5c, 0xe7, 0xcb, 0x21,
	0x74, 0x01, 0x35, 0x1a, 0x86, 0x63, 0xce, 0x9c, 0x54, 0x5b, 0xdb, 0x8a, 0xd2, 0x5a, 0x4d, 0xd9,
	0xd2, 0x50, 0x25, 0x25, 0x5c, 0xa5, 0x39, 0x0f, 0x7d, 0x07, 0x26, 0x73, 0x5d, 0xc2, 0xfd, 0xd1,
	0xe4, 0x9a, 0x0a, 0x70, 0xdc, 0x28, 0xbf, 0x4f, 0x0b, 0xb6, 0xeb, 0xb6, 0x67, 0x50, 0x5c, 0x63,
	0x79, 0x17, 0x7d, 0x0e, 0xa5, 0x11, 0xf5, 0x9d, 0x69, 0x03, 0x14, 0xc5, 0xe3, 0xd5, 0x14, 0x67,
	0x12, 0x82, 0x35, 0xd2, 0xfa, 0xa3, 0x00, 0xd5, 0x3c, 0x27, 0x32, 0xa1, 0xc0, 0x1d, 0x25, 0xe4,
	0x32, 0x16, 0x16, 0xfa, 0x1a, 0xb6, 0x64, 0x82, 0x44, 0x04, 0xa5, 0x48, 0xcd, 0x93, 0x83, 0x35,
	0x22, 0x6d, 0x3b, 0x78, 0x93, 0xab, 0x5f, 0xd4, 0x01, 0x73, 0x96, 0x17, 0x49, 0xa6, 0x21, 0x53,
	0x2a, 0x35, 0x17, 0x75, 0xb1, 0x3a, 0xb7, 0x81, 0x40, 0xe3, 0x1a, 0xcf, 0xbb, 0xe8, 0x53, 0x30,
	0x27, 0x31, 0x8b, 0x49, 0xc4, 0x3c, 0xca, 0x7d, 0xee, 0xbb, 0x4a, 0xb1, 0x25, 0x5c, 0x93, 0x51,
	0x9c, 0x05, 0xd1, 0x53, 0x80, 0xec, 0x51, 0x8a, 0x43, 0x4b, 0x25, 0x6e, 0xe0, 0x72, 0x1a, 0x11,
	0x87, 0x3a, 0x84, 0x1d, 0x21, 0xf7, 0x28, 0x21, 0xb7, 0x1e, 0x79, 0x4b, 0xc7, 0xe2, 0x3d, 0x28,
	0x79, 0x19, 0xb8, 0xa6, 0xc2, 0x97, 0xde, 0x1b, 0x15, 0x94, 0x9d, 0x46, 0xf8, 0x2e, 0xcb, 0x03,
	0xb7, 0x14, 0xd0, 0xd4, 0xf1, 0x0c, 0x69, 0xfd, 0x65, 0x40, 0x25, 0x77, 0xc3, 0xf9, 0x92, 0x19,
	0xff, 0xb7, 0x64, 0xdf, 0x42, 0x59, 0x7d, 0xab, 0xaa, 0xa5, 0x0b, 0xbe, 0xae, 0x2b, 0xa8, 0x52,
	0x6d, 0xf3, 0xd4, 0x42, 0x8f, 0xa1, 0xcc, 0xde, 0x85, 0x3c, 0x62, 0x44, 0x75, 0x3c, 0xd9, 0x1a,
	0xb7, 0x75, 0x40, 0x34, 0x45, 0x51, 0x9b, 0x4c, 0xb6, 0x9e, 0x7e, 0xf0, 0x45, 0x5c, 0x4e, 0x23,
	0x9d, 0xd8, 0xfa, 0x11, 0x6a, 0x0b, 0x02, 0x93, 0x32, 0x5f, 0x50, 0xa7, 0x48, 0xa8, 0x78, 0xb7,
	0xcc, 0xf3, 0xdf, 0xe2, 0x6a, 0x5e, 0x9b, 0x96, 0x0d, 0xd5, 0xfc, 0x23, 0x40, 0x5f, 0xa6, 0x8d,
	0x6f, 0x43, 0xf1, 0x1d, 0xac, 0x7d, 0x36, 0xba, 0xed, 0x59, 0x7f, 0x1b, 0xb0, 0xbb, 0xfc, 0x3e,
	0x3f, 0xa8, 0xde, 0x1d, 0xa8, 0xa6, 0x5d, 0x21, 0x5f, 0xf2, 0xe3, 0xfb, 0x75, 0x06, 0x55, 0xf9,
	0xca, 0x64, 0xee, 0xa0, 0x17, 0x80, 0xa8, 0xe3, 0xf0, 0x84, 0x07, 0x72, 0xa8, 0xc5, 0x02, 0x4b,
	0x5d, 0xad, 0xfa, 0x12, 0xae, 0xcf, 0x57, 0xfa, 0x7a, 0xc1, 0xfa, 0xd3, 0x80, 0xda, 0xc2, 0x54,
	0x91, 0x33, 0xd1, 0x0b, 0x1c, 0x7e, 0x23, 0x6f, 0x68, 0xd5, 0x4c, 0xcc, 0x16, 0x97, 0x66, 0xa2,
	0xc3, 0xc6, 0x2c, 0x49, 0x7b, 0x11, 0xb9, 0x65, 0xd3, 0x6c, 0x26, 0xa6, 0x71, 0x49, 0x7d, 0xc9,
	0xa6, 0xe8, 0x0d, 0xec, 0x2d, 0xce, 0x44, 0x3d, 0xb6, 0x8a, 0xf7, 0x6a, 0x87, 0xb3, 0x09, 0x54,
	0xe7, 0xcb, 0x21, 0xeb, 0xd7, 0xdc, 0x74, 0x9c, 0xf5, 0xc8, 0xe1, 0xca, 0xde, 0xab, 0x15, 0x74,
	0x78, 0xbf, 0x0a, 0xaf, 0x68, 0xbd, 0xd6, 0xcf, 0x50, 0x52, 0x2d, 0x0c, 0x7d, 0x03, 0xe5, 0x1b,
	0xea, 0xf1, 0xf1, 0xf4, 0x8e, 0x9b, 0xb7, 0xd5, 0xdf, 0x8f, 0x74, 0xf6, 0xbe, 0x56, 0x48, 0x71,
	0xf3, 0xdb, 0x37, 0xa9, 0x85, 0xf6, 0xb3, 0x76, 0x59, 0x50, 0xf7, 0xa3, 0x9d, 0xe3, 0x6b, 0xd8,
	0x5f, 0x75, 0xcf, 0xa8, 0x0e, 0xb5, 0x61, 0xef, 0x02, 0xb7, 0xce, 0x6d, 0x32, 0xbc, 0xea, 0xdb,
	0x83, 0xdd, 0x07, 0xe8, 0x63, 0x78, 0xd8, 0xbe, 0x3a, 0xc3, 0x76, 0xab, 0x6f, 0x93, 0xf6, 0xc0,
	0xee, 0x90, 0xfe, 0xa0, 0x8b, 0x5b, 0x17, 0xf6, 0xae, 0x81, 0x9e, 0x40, 0x63, 0xb6, 0xd4, 0xeb,
	0x5e, 0xda, 0x9d, 0xee, 0xd5, 0x6c, 0xb5, 0x70, 0xfc, 0x0a, 0x76, 0x97, 0x9b, 0x1d, 0xda, 0x83,
	0x1d, 0xf1, 0xc5, 0xf0, 0xb4, 0x25, 0x50, 0xb3, 0x1d, 0x3e, 0x02, 0x34, 0x0f, 0x9e, 0xb7, 0xfb,
	0x83, 0xd6, 0xd5, 0x99, 0xa0, 0x3f, 0x7d, 0xfe, 0xd3, 0x81, 0xcb, 0x93, 0x5f, 0x26, 0xd7, 0xcd,
	0x51, 0xe0, 0xbd, 0x0c, 0x6f, 0x3d, 0xdf, 0x0d, 0x5e, 0x08, 0x69, 0xbc, 0x0c, 0x03, 0x61, 0xa8,
	0x7f, 0x5c, 0x71, 0xef, 0x41, 0xcf, 0xe8, 0x15, 0x7a, 0xc5, 0xeb, 0x4d, 0xe5, 0x7f, 0xf1, 0x6f,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x6a, 0xb7, 0xb1, 0x54, 0xec, 0x09, 0x00, 0x00,
}
