// Code generated by protoc-gen-go.
// source: networking_envelopes.proto
// DO NOT EDIT!

package pogo_protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Ignoring public import of Request from networking_requests.proto

// Ignoring public import of RequestType from networking_requests.proto

// Ignoring public import of DailyBonus from data_player.proto

// Ignoring public import of ContactSettings from data_player.proto

// Ignoring public import of EquippedBadge from data_player.proto

// Ignoring public import of Currency from data_player.proto

// Ignoring public import of PlayerPublicProfile from data_player.proto

// Ignoring public import of PlayerStats from data_player.proto

// Ignoring public import of PlayerCamera from data_player.proto

// Ignoring public import of PlayerAvatar from data_player.proto

// Ignoring public import of PlayerCurrency from data_player.proto

// Ignoring public import of ItemData from inventory_item.proto

// Ignoring public import of ItemAward from inventory_item.proto

// Ignoring public import of ItemId from inventory_item.proto

// Ignoring public import of ItemType from inventory_item.proto

type Unknown6 struct {
	RequestType int32              `protobuf:"varint,1,opt,name=request_type,json=requestType" json:"request_type,omitempty"`
	Unknown2    *Unknown6_Unknown2 `protobuf:"bytes,2,opt,name=unknown2" json:"unknown2,omitempty"`
}

func (m *Unknown6) Reset()                    { *m = Unknown6{} }
func (m *Unknown6) String() string            { return proto.CompactTextString(m) }
func (*Unknown6) ProtoMessage()               {}
func (*Unknown6) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{0} }

func (m *Unknown6) GetUnknown2() *Unknown6_Unknown2 {
	if m != nil {
		return m.Unknown2
	}
	return nil
}

type Unknown6_Unknown2 struct {
	Unknown1 []byte `protobuf:"bytes,1,opt,name=unknown1,proto3" json:"unknown1,omitempty"`
}

func (m *Unknown6_Unknown2) Reset()                    { *m = Unknown6_Unknown2{} }
func (m *Unknown6_Unknown2) String() string            { return proto.CompactTextString(m) }
func (*Unknown6_Unknown2) ProtoMessage()               {}
func (*Unknown6_Unknown2) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{0, 0} }

type ResponseEnvelope struct {
	StatusCode int32               `protobuf:"varint,1,opt,name=status_code,json=statusCode" json:"status_code,omitempty"`
	RequestId  uint64              `protobuf:"varint,2,opt,name=request_id,json=requestId" json:"request_id,omitempty"`
	ApiUrl     string              `protobuf:"bytes,3,opt,name=api_url,json=apiUrl" json:"api_url,omitempty"`
	Unknown6   []*Unknown6Response `protobuf:"bytes,6,rep,name=unknown6" json:"unknown6,omitempty"`
	AuthTicket *AuthTicket         `protobuf:"bytes,7,opt,name=auth_ticket,json=authTicket" json:"auth_ticket,omitempty"`
	Returns    [][]byte            `protobuf:"bytes,100,rep,name=returns,proto3" json:"returns,omitempty"`
	Error      string              `protobuf:"bytes,101,opt,name=error" json:"error,omitempty"`
}

func (m *ResponseEnvelope) Reset()                    { *m = ResponseEnvelope{} }
func (m *ResponseEnvelope) String() string            { return proto.CompactTextString(m) }
func (*ResponseEnvelope) ProtoMessage()               {}
func (*ResponseEnvelope) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{1} }

func (m *ResponseEnvelope) GetUnknown6() []*Unknown6Response {
	if m != nil {
		return m.Unknown6
	}
	return nil
}

func (m *ResponseEnvelope) GetAuthTicket() *AuthTicket {
	if m != nil {
		return m.AuthTicket
	}
	return nil
}

type ResponseEnvelope_Unknown7 struct {
	Unknown71 []byte `protobuf:"bytes,1,opt,name=unknown71,proto3" json:"unknown71,omitempty"`
	Unknown72 int64  `protobuf:"varint,2,opt,name=unknown72" json:"unknown72,omitempty"`
	Unknown73 []byte `protobuf:"bytes,3,opt,name=unknown73,proto3" json:"unknown73,omitempty"`
}

func (m *ResponseEnvelope_Unknown7) Reset()                    { *m = ResponseEnvelope_Unknown7{} }
func (m *ResponseEnvelope_Unknown7) String() string            { return proto.CompactTextString(m) }
func (*ResponseEnvelope_Unknown7) ProtoMessage()               {}
func (*ResponseEnvelope_Unknown7) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{1, 0} }

type RequestEnvelope struct {
	StatusCode int32                     `protobuf:"varint,1,opt,name=status_code,json=statusCode" json:"status_code,omitempty"`
	RequestId  uint64                    `protobuf:"varint,3,opt,name=request_id,json=requestId" json:"request_id,omitempty"`
	Requests   []*Request                `protobuf:"bytes,4,rep,name=requests" json:"requests,omitempty"`
	Unknown6   []*Unknown6               `protobuf:"bytes,6,rep,name=unknown6" json:"unknown6,omitempty"`
	Latitude   float64                   `protobuf:"fixed64,7,opt,name=latitude" json:"latitude,omitempty"`
	Longitude  float64                   `protobuf:"fixed64,8,opt,name=longitude" json:"longitude,omitempty"`
	Altitude   float64                   `protobuf:"fixed64,9,opt,name=altitude" json:"altitude,omitempty"`
	AuthInfo   *RequestEnvelope_AuthInfo `protobuf:"bytes,10,opt,name=auth_info,json=authInfo" json:"auth_info,omitempty"`
	AuthTicket *AuthTicket               `protobuf:"bytes,11,opt,name=auth_ticket,json=authTicket" json:"auth_ticket,omitempty"`
	Unknown12  int64                     `protobuf:"varint,12,opt,name=unknown12" json:"unknown12,omitempty"`
}

func (m *RequestEnvelope) Reset()                    { *m = RequestEnvelope{} }
func (m *RequestEnvelope) String() string            { return proto.CompactTextString(m) }
func (*RequestEnvelope) ProtoMessage()               {}
func (*RequestEnvelope) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{2} }

func (m *RequestEnvelope) GetRequests() []*Request {
	if m != nil {
		return m.Requests
	}
	return nil
}

func (m *RequestEnvelope) GetUnknown6() []*Unknown6 {
	if m != nil {
		return m.Unknown6
	}
	return nil
}

func (m *RequestEnvelope) GetAuthInfo() *RequestEnvelope_AuthInfo {
	if m != nil {
		return m.AuthInfo
	}
	return nil
}

func (m *RequestEnvelope) GetAuthTicket() *AuthTicket {
	if m != nil {
		return m.AuthTicket
	}
	return nil
}

type RequestEnvelope_AuthInfo struct {
	Provider string                        `protobuf:"bytes,1,opt,name=provider" json:"provider,omitempty"`
	Token    *RequestEnvelope_AuthInfo_JWT `protobuf:"bytes,2,opt,name=token" json:"token,omitempty"`
}

func (m *RequestEnvelope_AuthInfo) Reset()                    { *m = RequestEnvelope_AuthInfo{} }
func (m *RequestEnvelope_AuthInfo) String() string            { return proto.CompactTextString(m) }
func (*RequestEnvelope_AuthInfo) ProtoMessage()               {}
func (*RequestEnvelope_AuthInfo) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{2, 0} }

func (m *RequestEnvelope_AuthInfo) GetToken() *RequestEnvelope_AuthInfo_JWT {
	if m != nil {
		return m.Token
	}
	return nil
}

type RequestEnvelope_AuthInfo_JWT struct {
	Contents string `protobuf:"bytes,1,opt,name=contents" json:"contents,omitempty"`
	Unknown2 int32  `protobuf:"varint,2,opt,name=unknown2" json:"unknown2,omitempty"`
}

func (m *RequestEnvelope_AuthInfo_JWT) Reset()         { *m = RequestEnvelope_AuthInfo_JWT{} }
func (m *RequestEnvelope_AuthInfo_JWT) String() string { return proto.CompactTextString(m) }
func (*RequestEnvelope_AuthInfo_JWT) ProtoMessage()    {}
func (*RequestEnvelope_AuthInfo_JWT) Descriptor() ([]byte, []int) {
	return fileDescriptor8, []int{2, 0, 0}
}

type Unknown6Response struct {
	ResponseType int32                      `protobuf:"varint,1,opt,name=response_type,json=responseType" json:"response_type,omitempty"`
	Unknown2     *Unknown6Response_Unknown2 `protobuf:"bytes,2,opt,name=unknown2" json:"unknown2,omitempty"`
}

func (m *Unknown6Response) Reset()                    { *m = Unknown6Response{} }
func (m *Unknown6Response) String() string            { return proto.CompactTextString(m) }
func (*Unknown6Response) ProtoMessage()               {}
func (*Unknown6Response) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{3} }

func (m *Unknown6Response) GetUnknown2() *Unknown6Response_Unknown2 {
	if m != nil {
		return m.Unknown2
	}
	return nil
}

type Unknown6Response_Unknown2 struct {
	Unknown1         uint64                                 `protobuf:"varint,1,opt,name=unknown1" json:"unknown1,omitempty"`
	Items            []*Unknown6Response_Unknown2_StoreItem `protobuf:"bytes,2,rep,name=items" json:"items,omitempty"`
	PlayerCurrencies []*Currency                            `protobuf:"bytes,3,rep,name=player_currencies,json=playerCurrencies" json:"player_currencies,omitempty"`
	Unknown4         string                                 `protobuf:"bytes,4,opt,name=unknown4" json:"unknown4,omitempty"`
}

func (m *Unknown6Response_Unknown2) Reset()                    { *m = Unknown6Response_Unknown2{} }
func (m *Unknown6Response_Unknown2) String() string            { return proto.CompactTextString(m) }
func (*Unknown6Response_Unknown2) ProtoMessage()               {}
func (*Unknown6Response_Unknown2) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{3, 0} }

func (m *Unknown6Response_Unknown2) GetItems() []*Unknown6Response_Unknown2_StoreItem {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *Unknown6Response_Unknown2) GetPlayerCurrencies() []*Currency {
	if m != nil {
		return m.PlayerCurrencies
	}
	return nil
}

type Unknown6Response_Unknown2_StoreItem struct {
	ItemId         string                                     `protobuf:"bytes,1,opt,name=item_id,json=itemId" json:"item_id,omitempty"`
	IsIap          bool                                       `protobuf:"varint,2,opt,name=is_iap,json=isIap" json:"is_iap,omitempty"`
	CurrencyToBuy  *Currency                                  `protobuf:"bytes,3,opt,name=currency_to_buy,json=currencyToBuy" json:"currency_to_buy,omitempty"`
	YieldsCurrency *Currency                                  `protobuf:"bytes,4,opt,name=yields_currency,json=yieldsCurrency" json:"yields_currency,omitempty"`
	YieldsItem     *ItemData                                  `protobuf:"bytes,5,opt,name=yields_item,json=yieldsItem" json:"yields_item,omitempty"`
	Tags           []*Unknown6Response_Unknown2_StoreItem_Tag `protobuf:"bytes,6,rep,name=tags" json:"tags,omitempty"`
	Unknown7       int32                                      `protobuf:"varint,7,opt,name=unknown7" json:"unknown7,omitempty"`
}

func (m *Unknown6Response_Unknown2_StoreItem) Reset()         { *m = Unknown6Response_Unknown2_StoreItem{} }
func (m *Unknown6Response_Unknown2_StoreItem) String() string { return proto.CompactTextString(m) }
func (*Unknown6Response_Unknown2_StoreItem) ProtoMessage()    {}
func (*Unknown6Response_Unknown2_StoreItem) Descriptor() ([]byte, []int) {
	return fileDescriptor8, []int{3, 0, 0}
}

func (m *Unknown6Response_Unknown2_StoreItem) GetCurrencyToBuy() *Currency {
	if m != nil {
		return m.CurrencyToBuy
	}
	return nil
}

func (m *Unknown6Response_Unknown2_StoreItem) GetYieldsCurrency() *Currency {
	if m != nil {
		return m.YieldsCurrency
	}
	return nil
}

func (m *Unknown6Response_Unknown2_StoreItem) GetYieldsItem() *ItemData {
	if m != nil {
		return m.YieldsItem
	}
	return nil
}

func (m *Unknown6Response_Unknown2_StoreItem) GetTags() []*Unknown6Response_Unknown2_StoreItem_Tag {
	if m != nil {
		return m.Tags
	}
	return nil
}

type Unknown6Response_Unknown2_StoreItem_Tag struct {
	Key   string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
}

func (m *Unknown6Response_Unknown2_StoreItem_Tag) Reset() {
	*m = Unknown6Response_Unknown2_StoreItem_Tag{}
}
func (m *Unknown6Response_Unknown2_StoreItem_Tag) String() string { return proto.CompactTextString(m) }
func (*Unknown6Response_Unknown2_StoreItem_Tag) ProtoMessage()    {}
func (*Unknown6Response_Unknown2_StoreItem_Tag) Descriptor() ([]byte, []int) {
	return fileDescriptor8, []int{3, 0, 0, 0}
}

type AuthTicket struct {
	Start             []byte `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	ExpireTimestampMs uint64 `protobuf:"varint,2,opt,name=expire_timestamp_ms,json=expireTimestampMs" json:"expire_timestamp_ms,omitempty"`
	End               []byte `protobuf:"bytes,3,opt,name=end,proto3" json:"end,omitempty"`
}

func (m *AuthTicket) Reset()                    { *m = AuthTicket{} }
func (m *AuthTicket) String() string            { return proto.CompactTextString(m) }
func (*AuthTicket) ProtoMessage()               {}
func (*AuthTicket) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{4} }

func init() {
	proto.RegisterType((*Unknown6)(nil), "POGOProtos.Networking.Envelopes.Unknown6")
	proto.RegisterType((*Unknown6_Unknown2)(nil), "POGOProtos.Networking.Envelopes.Unknown6.Unknown2")
	proto.RegisterType((*ResponseEnvelope)(nil), "POGOProtos.Networking.Envelopes.ResponseEnvelope")
	proto.RegisterType((*ResponseEnvelope_Unknown7)(nil), "POGOProtos.Networking.Envelopes.ResponseEnvelope.Unknown7")
	proto.RegisterType((*RequestEnvelope)(nil), "POGOProtos.Networking.Envelopes.RequestEnvelope")
	proto.RegisterType((*RequestEnvelope_AuthInfo)(nil), "POGOProtos.Networking.Envelopes.RequestEnvelope.AuthInfo")
	proto.RegisterType((*RequestEnvelope_AuthInfo_JWT)(nil), "POGOProtos.Networking.Envelopes.RequestEnvelope.AuthInfo.JWT")
	proto.RegisterType((*Unknown6Response)(nil), "POGOProtos.Networking.Envelopes.Unknown6Response")
	proto.RegisterType((*Unknown6Response_Unknown2)(nil), "POGOProtos.Networking.Envelopes.Unknown6Response.Unknown2")
	proto.RegisterType((*Unknown6Response_Unknown2_StoreItem)(nil), "POGOProtos.Networking.Envelopes.Unknown6Response.Unknown2.StoreItem")
	proto.RegisterType((*Unknown6Response_Unknown2_StoreItem_Tag)(nil), "POGOProtos.Networking.Envelopes.Unknown6Response.Unknown2.StoreItem.Tag")
	proto.RegisterType((*AuthTicket)(nil), "POGOProtos.Networking.Envelopes.AuthTicket")
}

func init() { proto.RegisterFile("networking_envelopes.proto", fileDescriptor8) }

var fileDescriptor8 = []byte{
	// 927 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xac, 0x56, 0xdd, 0x6f, 0xdb, 0x54,
	0x14, 0x27, 0x73, 0x93, 0x25, 0x27, 0x19, 0x6d, 0x2f, 0x43, 0x18, 0x0b, 0xb4, 0x2e, 0x95, 0xf8,
	0x10, 0x9a, 0xa7, 0xa4, 0xa8, 0x15, 0x48, 0x7b, 0x60, 0xed, 0xc4, 0x82, 0xd8, 0x16, 0xdd, 0x65,
	0x43, 0x9a, 0x90, 0x2c, 0x37, 0xbe, 0x64, 0x56, 0x1c, 0x5f, 0x73, 0xef, 0x75, 0x87, 0xff, 0x19,
	0xde, 0x78, 0xe6, 0x85, 0x27, 0x5e, 0x10, 0xff, 0x19, 0xf7, 0xd3, 0x36, 0x1d, 0xd0, 0x52, 0x78,
	0x89, 0xce, 0xc7, 0x3d, 0xdf, 0xc7, 0xbf, 0x13, 0x08, 0x72, 0x22, 0x5e, 0x51, 0xb6, 0x4e, 0xf3,
	0x55, 0x44, 0xf2, 0x33, 0x92, 0xd1, 0x82, 0xf0, 0xb0, 0x60, 0x54, 0x50, 0x74, 0x6b, 0xfe, 0xe4,
	0xcb, 0x27, 0x73, 0x45, 0xf2, 0xf0, 0x71, 0xfd, 0x2c, 0x7c, 0xe0, 0x9e, 0x05, 0xef, 0xb6, 0x8c,
	0x19, 0xf9, 0xbe, 0x24, 0x5c, 0x58, 0xdb, 0x60, 0x37, 0x89, 0x45, 0x1c, 0x15, 0x59, 0x5c, 0x11,
	0x66, 0x45, 0x37, 0x53, 0x69, 0x98, 0x0b, 0xca, 0xaa, 0x28, 0x15, 0x64, 0x63, 0xa4, 0xe3, 0x9f,
	0x3a, 0xd0, 0x7f, 0x96, 0xaf, 0x73, 0xfa, 0x2a, 0x3f, 0x44, 0xb7, 0x61, 0x64, 0xfd, 0x44, 0xa2,
	0x2a, 0x88, 0xdf, 0xd9, 0xeb, 0x7c, 0xd4, 0xc5, 0x43, 0x2b, 0x5b, 0x48, 0x11, 0x7a, 0x0c, 0xfd,
	0xd2, 0x3c, 0x9f, 0xfa, 0xd7, 0xa4, 0x7a, 0x38, 0x9d, 0x86, 0x17, 0xe4, 0x19, 0x3a, 0xff, 0x8e,
	0x98, 0xe2, 0xda, 0x47, 0xf0, 0x41, 0x1d, 0x7e, 0x8a, 0x82, 0xda, 0xf7, 0x44, 0x87, 0x1e, 0xd5,
	0xef, 0x26, 0xe3, 0x1f, 0x3d, 0xd8, 0xc1, 0x84, 0x17, 0x34, 0xe7, 0xc4, 0x79, 0x46, 0xb7, 0x60,
	0xc8, 0x45, 0x2c, 0x4a, 0x1e, 0x2d, 0x69, 0xe2, 0xd2, 0x05, 0x23, 0x3a, 0x96, 0x12, 0xf4, 0x3e,
	0x80, 0x2b, 0x28, 0x4d, 0x74, 0xbe, 0x5b, 0x78, 0x60, 0x25, 0xb3, 0x04, 0xbd, 0x03, 0xd7, 0xe3,
	0x22, 0x8d, 0x4a, 0x96, 0xf9, 0x9e, 0xd4, 0x0d, 0x70, 0x4f, 0xb2, 0xcf, 0x58, 0x86, 0x1e, 0xd5,
	0x99, 0x1c, 0xfa, 0xbd, 0x3d, 0x4f, 0x56, 0x39, 0xb9, 0x74, 0x95, 0x2e, 0xcb, 0x3a, 0xf9, 0x43,
	0xf4, 0x35, 0x0c, 0xe3, 0x52, 0xbc, 0x8c, 0x44, 0xba, 0x5c, 0x13, 0xe1, 0x5f, 0xd7, 0x7d, 0xfb,
	0xe4, 0x42, 0x8f, 0x5f, 0x48, 0x9b, 0x85, 0x36, 0xc1, 0x10, 0xd7, 0x34, 0xf2, 0xe1, 0x3a, 0x23,
	0xa2, 0x64, 0x39, 0xf7, 0x13, 0x99, 0xdb, 0x08, 0x3b, 0x16, 0xdd, 0x84, 0x2e, 0x61, 0x8c, 0x32,
	0x9f, 0xe8, 0x6a, 0x0c, 0x13, 0x24, 0x75, 0x8b, 0x8f, 0xd0, 0x7b, 0x30, 0xb0, 0x59, 0x1d, 0xb9,
	0x1e, 0x37, 0x82, 0xb6, 0xd6, 0x4c, 0xd7, 0x6b, 0xb4, 0xd3, 0xb6, 0xf6, 0x40, 0xf7, 0xab, 0x65,
	0x7b, 0x30, 0xfe, 0xa5, 0x0b, 0xdb, 0xd8, 0x74, 0xf6, 0xaa, 0xf3, 0xf1, 0xce, 0xcf, 0xe7, 0x18,
	0xfa, 0x6e, 0xaf, 0xfd, 0x2d, 0x3d, 0x86, 0x0f, 0xff, 0xa6, 0x69, 0xd8, 0xad, 0xbf, 0x25, 0x70,
	0x6d, 0x88, 0x1e, 0xbc, 0x36, 0xcb, 0x8f, 0x2f, 0x3f, 0xcb, 0x66, 0x86, 0x72, 0x39, 0xb3, 0x58,
	0xa4, 0xa2, 0x94, 0x85, 0xa8, 0x01, 0x76, 0x70, 0xcd, 0xab, 0xce, 0x64, 0x34, 0x5f, 0x19, 0x65,
	0x5f, 0x2b, 0x1b, 0x81, 0xb2, 0x8c, 0x33, 0x6b, 0x39, 0x30, 0x96, 0x8e, 0x47, 0xcf, 0x61, 0xa0,
	0x37, 0x23, 0xcd, 0xbf, 0xa3, 0x3e, 0xe8, 0xbd, 0xf8, 0xec, 0xc2, 0xec, 0xce, 0xb5, 0x59, 0xef,
	0xc9, 0x4c, 0x3a, 0x90, 0x7e, 0x2d, 0x75, 0x7e, 0xe3, 0x86, 0xff, 0x6d, 0xe3, 0x9a, 0xc9, 0x4f,
	0xa6, 0xfe, 0xe8, 0x4f, 0x7b, 0x31, 0x99, 0x06, 0xbf, 0x4a, 0x08, 0x71, 0x29, 0xa8, 0x62, 0x25,
	0xb0, 0x9c, 0xa5, 0x09, 0x61, 0x7a, 0xde, 0x03, 0x5c, 0xf3, 0xe8, 0x29, 0x74, 0x05, 0x5d, 0x93,
	0xdc, 0x02, 0xc7, 0xbd, 0x2b, 0x17, 0x1a, 0x7e, 0xf5, 0xcd, 0x02, 0x1b, 0x5f, 0xc1, 0x3d, 0xf0,
	0x24, 0xa7, 0xe2, 0x2e, 0x69, 0x2e, 0x24, 0xc0, 0x71, 0x17, 0xd7, 0xf1, 0x2d, 0x5c, 0x31, 0x5b,
	0xdd, 0x6d, 0xf0, 0x67, 0xfc, 0x7b, 0x0f, 0x76, 0xce, 0x7f, 0xb9, 0x68, 0x1f, 0x6e, 0x30, 0x4b,
	0xb7, 0x81, 0x70, 0xe4, 0x84, 0x1a, 0x09, 0x9f, 0xbf, 0x86, 0x84, 0x9f, 0xff, 0x6b, 0x8c, 0xf8,
	0x2b, 0x44, 0xfc, 0xb9, 0xfb, 0x0f, 0x90, 0xb8, 0xd5, 0x40, 0x22, 0x7a, 0x01, 0x5d, 0x05, 0xe4,
	0x5c, 0x46, 0x57, 0x5b, 0x7d, 0x72, 0xf5, 0xe8, 0xe1, 0x53, 0x79, 0x16, 0xc8, 0x4c, 0x3a, 0xc3,
	0xc6, 0xa5, 0x04, 0xc0, 0x5d, 0x73, 0x3c, 0xa2, 0x65, 0xc9, 0x18, 0xc9, 0x97, 0x29, 0xe1, 0xf2,
	0xfb, 0x54, 0x71, 0xf6, 0xda, 0x71, 0x4e, 0xe4, 0x99, 0x09, 0xe7, 0xe6, 0xcc, 0x1c, 0x9b, 0x97,
	0x15, 0xde, 0x31, 0xa6, 0xc7, 0xb5, 0x65, 0xab, 0x8c, 0x4f, 0xe5, 0x87, 0xac, 0xa7, 0xe3, 0xf8,
	0xe0, 0x37, 0x0f, 0x06, 0x75, 0x7c, 0x05, 0xc9, 0x2a, 0x03, 0x05, 0x07, 0x66, 0x8c, 0x3d, 0xc5,
	0x4a, 0x2c, 0x78, 0x1b, 0x7a, 0x29, 0x8f, 0xd2, 0xb8, 0xd0, 0xcd, 0xee, 0xcb, 0x44, 0xf9, 0x2c,
	0x2e, 0xd0, 0x43, 0xd8, 0xb6, 0x19, 0x56, 0x91, 0xa0, 0xd1, 0x69, 0x59, 0x69, 0x18, 0xb9, 0x4c,
	0x9a, 0x37, 0x9c, 0xe1, 0x82, 0xde, 0x2f, 0x2b, 0x34, 0x83, 0xed, 0x2a, 0x25, 0x59, 0xc2, 0x5d,
	0xc9, 0x95, 0x4e, 0xf5, 0x32, 0x9e, 0xde, 0x34, 0x86, 0x8e, 0x47, 0x27, 0x30, 0xb4, 0xae, 0x54,
	0xf2, 0x7e, 0x57, 0xbb, 0xd9, 0x6f, 0xbb, 0x99, 0xb9, 0x5b, 0x1c, 0xaa, 0xaa, 0xf5, 0x8f, 0xf2,
	0x8c, 0xc1, 0xd8, 0xe9, 0x56, 0x7c, 0x0b, 0x5b, 0x22, 0x5e, 0x71, 0x0b, 0x5a, 0x0f, 0xff, 0x8f,
	0xf1, 0x86, 0x8b, 0x78, 0x85, 0xb5, 0xd7, 0xd6, 0x48, 0x8e, 0x34, 0x9e, 0x35, 0x1f, 0xc5, 0x51,
	0x70, 0x07, 0x3c, 0xf9, 0x10, 0xed, 0x80, 0xb7, 0x26, 0x95, 0x9d, 0x83, 0x22, 0xd5, 0x81, 0x39,
	0x8b, 0xb3, 0x92, 0xe8, 0x19, 0xc8, 0x03, 0xa3, 0x99, 0x71, 0x02, 0xd0, 0x00, 0x87, 0x7a, 0x23,
	0x11, 0x9e, 0x09, 0x7b, 0x5e, 0x0c, 0x83, 0x42, 0x78, 0x8b, 0xfc, 0x50, 0xa4, 0x4c, 0x7e, 0x50,
	0xe9, 0x46, 0x7e, 0xd3, 0xf1, 0xa6, 0x88, 0xf4, 0xea, 0xaa, 0x9d, 0xde, 0x35, 0xaa, 0x85, 0xd3,
	0x3c, 0xe2, 0x2a, 0x36, 0xc9, 0x13, 0x7b, 0x66, 0x14, 0x79, 0x7f, 0xff, 0xc5, 0x6d, 0x09, 0xa8,
	0x2f, 0xcb, 0xd3, 0x70, 0x49, 0x37, 0x77, 0x8b, 0xf5, 0x26, 0x5f, 0xd1, 0x3b, 0x34, 0x49, 0xef,
	0x16, 0x54, 0x12, 0xfa, 0xdf, 0x0c, 0x9f, 0xbf, 0x31, 0xef, 0xcc, 0xaf, 0x9d, 0xf6, 0x34, 0x77,
	0xf0, 0x47, 0x00, 0x00, 0x00, 0xff, 0xff, 0xdb, 0x77, 0xc7, 0x32, 0x5e, 0x09, 0x00, 0x00,
}
